# Generated by Django 4.0 on 2021-12-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Company_Name', models.CharField(blank=True, max_length=500, null=True)),
                ('Company_Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Company_Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Company_Phone', models.CharField(blank=True, max_length=50, null=True)),
                ('Company_Fax', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
