# Generated by Django 4.0 on 2021-12-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_company_information_create_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_information',
            name='Company_Short_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company_information',
            name='Company_Web_site',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
