# Generated by Django 4.0 on 2021-12-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_company_information_company_short_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_information',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
