# Generated by Django 4.0 on 2021-12-26 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0004_company_information_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch_Infoamtion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Branch_Name', models.CharField(blank=True, max_length=500, null=True)),
                ('Branch_Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Branch_Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Branch_Phone', models.CharField(blank=True, max_length=50, null=True)),
                ('Branch_Fax', models.CharField(blank=True, max_length=50, null=True)),
                ('Branch_Short_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('issu_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
