# Generated by Django 4.0 on 2021-12-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_userprofilem'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_information',
            name='Edits',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
