# Generated by Django 4.0 on 2021-12-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_company_information_edits'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_infoamtion',
            name='Edits',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
