# Generated by Django 4.0 on 2021-12-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_branch_infoamtion_edits'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartementM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
