# Generated by Django 4.0 on 2021-12-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0010_departementm_create_user_departementm_issu_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepartementM',
            new_name='DepartmentM',
        ),
    ]
