# Generated by Django 4.0 on 2021-12-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_rename_departementm_departmentm'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentm',
            name='Edits',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
