# Generated by Django 4.0 on 2022-01-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_bank_branchm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software_Permittion_MainM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Main_Name', models.CharField(blank=True, max_length=300, null=True)),
                ('Sub_Name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
