# Generated by Django 4.0 on 2022-01-01 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_software_permittion_mainm_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software_permittion_branch',
            name='Software_Permition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.software_permittion_mainm'),
        ),
    ]
