# Generated by Django 4.0 on 2022-01-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_software_permittion_branch_software_permition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software_permittion_mainm',
            name='user',
        ),
    ]
