# Generated by Django 4.0 on 2022-01-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_remove_software_permittion_mainm_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module_Name',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Module_Name', models.CharField(blank=True, max_length=700, null=True)),
            ],
        ),
    ]
