# Generated by Django 4.0 on 2022-01-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_module_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module_Name',
        ),
        migrations.RemoveField(
            model_name='userprofilem',
            name='Branch_code',
        ),
    ]
