# Generated by Django 4.0 on 2022-01-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_remove_software_permittion_branch_software_permition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Product_Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
