# Generated by Django 4.0 on 2022-01-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_inventory_product_entry_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory_product_entry',
            old_name='user',
            new_name='userc',
        ),
    ]
