# Generated by Django 4.0 on 2022-01-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_rename_user_inventory_product_entry_userc'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_product_entry',
            name='Edits',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inventory_product_entry',
            name='issu_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
