# Generated by Django 4.0 on 2022-01-19 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0026_inventory_product_entry_edits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Supplier_Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Supplier_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Supplier_Address', models.CharField(blank=True, max_length=500, null=True)),
                ('Supplier_Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Supplier_Email', models.CharField(blank=True, max_length=50, null=True)),
                ('issu_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Edits', models.CharField(blank=True, max_length=10, null=True)),
                ('userc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
