# Generated by Django 4.0 on 2022-01-22 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0027_inventory_supplier_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hr_Employees_infoM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Employees_Name', models.CharField(blank=True, max_length=300, null=True)),
                ('Present_Address', models.CharField(blank=True, max_length=600, null=True)),
                ('Permanent_Address', models.CharField(blank=True, max_length=600, null=True)),
                ('Phone', models.CharField(blank=True, max_length=30, null=True)),
                ('Employees_Father_name', models.CharField(blank=True, max_length=300, null=True)),
                ('Employees_Mother_name', models.CharField(blank=True, max_length=300, null=True)),
                ('Employees_Blood', models.CharField(blank=True, max_length=30, null=True)),
                ('Employees_NID', models.CharField(blank=True, max_length=30, null=True)),
                ('Last_Education_Qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('Last_Education_CGPA', models.CharField(blank=True, max_length=100, null=True)),
                ('Employees_Date_of_Birth', models.DateField()),
                ('Appointment_Date', models.DateField()),
                ('Joining_Date', models.DateField()),
                ('issu_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Edits', models.CharField(blank=True, max_length=10, null=True)),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.departmentm')),
                ('Designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.designationm')),
                ('userc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
