# Generated by Django 4.0 on 2022-01-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_product_purchasem_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_purchasem',
            name='Oranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_purchasem',
            name='Oranty_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
