# Generated by Django 4.0 on 2022-01-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_product_purchasem_oranty_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_purchasem',
            name='Oranty_start_date',
            field=models.DateField(null=True),
        ),
    ]
