# Generated by Django 4.0 on 2022-01-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_alter_product_purchasem_oranty_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_purchasem',
            name='Oranty_start_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
