# Generated by Django 4.0 on 2022-01-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_alter_product_purchasem_oranty_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_purchasem',
            name='Oranty_year',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
