# Generated by Django 4.0 on 2022-02-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_hr_employees_infom_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_purchasem',
            name='Oranty_year',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
