# Generated by Django 4.0 on 2022-02-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_alter_product_purchasem_oranty_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_purchasem',
            name='Oranty_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
