# Generated by Django 4.0 on 2022-03-13 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0041_voyageform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyageform',
            name='User_Branch',
        ),
        migrations.AddField(
            model_name='voyageform',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
