# Generated by Django 4.0 on 2022-03-16 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0048_insuracetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarineQuatationM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Bill_date', models.DateField(auto_now=True)),
                ('Bill_No', models.CharField(blank=True, max_length=255, null=True)),
                ('Interest_covered', models.CharField(blank=True, max_length=1000, null=True)),
                ('Sdate', models.DateField(blank=True, null=True)),
                ('Edate', models.DateField(blank=True, null=True)),
                ('Sum_insured', models.IntegerField(blank=True, null=True)),
                ('Extra1', models.IntegerField(blank=True, null=True)),
                ('Extra2', models.IntegerField(blank=True, null=True)),
                ('Currency', models.IntegerField(blank=True, null=True)),
                ('Excrate', models.IntegerField(blank=True, null=True)),
                ('Bdtamount', models.IntegerField(blank=True, null=True)),
                ('Declaration', models.CharField(blank=True, max_length=600, null=True)),
                ('SpDeclaration', models.CharField(blank=True, max_length=600, null=True)),
                ('Bank_Branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.bank_branchm')),
                ('Bank_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.bankm')),
                ('Client_AddressM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.client_branchm')),
                ('Client_NameM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.clinetm')),
                ('Insurance_Type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.insuracetype')),
                ('Producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.hr_employees_infom')),
                ('RiskCover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.riskcovered')),
                ('Transit_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.transitby')),
                ('Voyage_From', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.voyageform')),
                ('Voyage_To', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.voyageto')),
                ('Voyage_Via', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.voyagevia')),
            ],
        ),
    ]
