# Generated by Django 4.0 on 2022-03-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0049_marinequatationm'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitby',
            name='Stump_Rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
