# Generated by Django 4.0 on 2022-03-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0050_transitby_stump_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marinequatationm',
            name='Transit_By',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
