# Generated by Django 4.0 on 2022-03-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0051_alter_marinequatationm_transit_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitby',
            name='Stump_Rate',
        ),
    ]
