# Generated by Django 4.0 on 2022-03-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0053_transitby_stump_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marinequatationm',
            name='Transit_By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.transitby'),
        ),
    ]
