# Generated by Django 4.0 on 2022-03-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0067_marinequatationm_ac_marinequatationm_bank_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marinequatationm',
            name='Currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
