# Generated by Django 4.0 on 2022-04-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0068_alter_marinequatationm_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='marinequatationm',
            name='sendmail',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
