# Generated by Django 4.0 on 2022-04-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0069_marinequatationm_sendmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_information',
            name='authorization',
            field=models.ImageField(blank=True, null=True, upload_to='authorization'),
        ),
    ]
