# Generated by Django 4.0 on 2022-04-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0071_rename_authorization_company_information_authorization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marinecovernotem',
            name='Sum_insured',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marinequatationm',
            name='Sum_insured',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
