# Generated by Django 4.0 on 2022-04-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0073_alter_marinecovernotem_cover_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='marinecovernotem',
            name='Cover_No_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
