# Generated by Django 4.0 on 2022-04-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0074_marinecovernotem_cover_no_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='covernover_banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cv_banner', models.ImageField(blank=True, null=True, upload_to='cv')),
            ],
        ),
    ]
