# Generated by Django 4.0 on 2022-04-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0077_marinecovernotem_mr_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='marinecovernotem',
            name='Printed_No',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
