# Generated by Django 4.0 on 2022-04-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0078_marinecovernotem_printed_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModOfPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
