# Generated by Django 4.0 on 2022-04-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0083_alter_mrtable_bank_address_alter_mrtable_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrtable',
            name='Gross_Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mrtable',
            name='Net_Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mrtable',
            name='Stump_Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mrtable',
            name='Vat_Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
