# Generated by Django 4.0 on 2022-04-27 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0089_marinecovernotem_coins_leader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarineAddendumM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Bill_No', models.CharField(blank=True, max_length=255, null=True)),
                ('Cover_No', models.CharField(blank=True, max_length=255, null=True)),
                ('Cover_No_no', models.CharField(blank=True, max_length=255, null=True)),
                ('Ac', models.CharField(blank=True, max_length=255, null=True)),
                ('Interest_covered', models.CharField(blank=True, max_length=1000, null=True)),
                ('Sum_insured', models.FloatField(blank=True, null=True)),
                ('Extra1', models.IntegerField(blank=True, null=True)),
                ('Extra2', models.IntegerField(blank=True, null=True)),
                ('Currency', models.CharField(blank=True, max_length=20, null=True)),
                ('Excrate', models.FloatField(blank=True, null=True)),
                ('Bdtamount', models.IntegerField(blank=True, null=True)),
                ('Discount', models.IntegerField(blank=True, null=True)),
                ('SpDiscount', models.IntegerField(blank=True, null=True)),
                ('Marine_Rate', models.FloatField(blank=True, null=True)),
                ('Marine_Amount', models.IntegerField(blank=True, null=True)),
                ('Ware_Rate', models.FloatField(blank=True, null=True)),
                ('Ware_Amount', models.IntegerField(blank=True, null=True)),
                ('Net_Amount', models.IntegerField(blank=True, null=True)),
                ('Vat_Amount', models.IntegerField(blank=True, null=True)),
                ('Stump_Amount', models.IntegerField(blank=True, null=True)),
                ('Gross_Amount', models.IntegerField(blank=True, null=True)),
                ('sendmail', models.CharField(blank=True, max_length=1000, null=True)),
                ('issu_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Edits', models.CharField(blank=True, max_length=10, null=True)),
                ('Printed_No', models.CharField(blank=True, max_length=255, null=True)),
                ('Coins_Leader', models.CharField(blank=True, max_length=20, null=True)),
                ('Coins_None_Leader', models.CharField(blank=True, max_length=20, null=True)),
                ('Coins_Leader_Persent', models.CharField(blank=True, max_length=20, null=True)),
                ('Coins_Leader_Doc', models.CharField(blank=True, max_length=20, null=True)),
                ('Coins_Leader_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Addendum_number', models.CharField(blank=True, max_length=255, null=True)),
                ('Addendum_no', models.CharField(blank=True, max_length=50, null=True)),
                ('Addendum_Date', models.DateField(blank=True, null=True)),
                ('narration', models.TextField(blank=True, max_length=1000, null=True)),
                ('narration_on', models.TextField(blank=True, max_length=1000, null=True)),
                ('Bank_Branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.bank_branchm')),
                ('Bank_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.bankm')),
                ('Client_AddressM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.client_branchm')),
                ('Client_NameM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.clinetm')),
                ('Insurance_Type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.insuracetype')),
                ('MR_Number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.mrtable')),
                ('Producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.hr_employees_infom')),
                ('RiskCover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.riskcovered')),
                ('Transit_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.transitby')),
                ('User_Branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.branch_infoamtion')),
                ('Voyage_From', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.voyageform')),
                ('Voyage_To', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.voyageto')),
                ('Voyage_Via', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.voyagevia')),
                ('userc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
