# Generated by Django 4.0 on 2022-05-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0090_marineaddendumm'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_information',
            name='Authlink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company_information',
            name='Logolink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
